project:
  type: book

book:
  title: "Documentation"
  author: "Brian C. Helsel"
  date: "6/26/2026"
  chapters:
    - index.qmd
    - clinical-core.qmd
    - genomics.qmd
    - pnt1.qmd
    - p217.qmd
    - proteomics.qmd
    - faq.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - lumen
      - custom.scss
    include-in-header:
      text: |
        <link href="https://unpkg.com/tabulator-tables@6.3.0/dist/css/tabulator.min.css" rel="stylesheet">
        <script src="https://unpkg.com/tabulator-tables@6.3.0/dist/js/tabulator.min.js"></script>
  pdf:
    documentclass: scrreprt

resources:
  - data/ProteomicsTableOne.json
  - data/ProteomicsTableTwo.json
