project:
  type: book

book:
  title: "Documentation"
  author: "Brian C. Helsel"
  date: "6/26/2026"
  chapters:
    - index.qmd
    - methods/centiloid.qmd
    - methods/clinical-core.qmd
    - methods/csf/csf.qmd
    - methods/genomics.qmd
    - methods/metabolomics.qmd
    - methods/mri/mri.qmd
    - methods/pnt1.qmd
    - methods/p217.qmd
    - methods/proteomics/proteomics.qmd
    - methods/safety-labs.qmd
    - methods/faq.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - lumen
      - custom.scss
    include-in-header:
      text: |
        <link href="https://unpkg.com/tabulator-tables@6.3.0/dist/css/tabulator.min.css" rel="stylesheet">
        <script src="https://unpkg.com/tabulator-tables@6.3.0/dist/js/tabulator.min.js"></script>

resources:
  - data/ProteomicsTableOne.json
  - data/ProteomicsTableTwo.json
